// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-xDl1s2cqBWJSPF0f8Ew886tNdRGd2QE',
    appId: '1:329891616896:android:431160dc3ed5218a14ee65',
    messagingSenderId: '329891616896',
    projectId: 'birthdaysreminder-2022',
    storageBucket: 'birthdaysreminder-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrn_oPZIixtzQi0cKBMreihZ2vag9IDUA',
    appId: '1:329891616896:ios:e2495f27e6f0a6ac14ee65',
    messagingSenderId: '329891616896',
    projectId: 'birthdaysreminder-2022',
    storageBucket: 'birthdaysreminder-2022.appspot.com',
    androidClientId: '329891616896-4dgvitkutqg6imone1om1k9pj3bchj76.apps.googleusercontent.com',
    iosClientId: '329891616896-uibdjbsltvacc52ks3pp77ikidr2feui.apps.googleusercontent.com',
    iosBundleId: 'it.giuug.birthdaysreminder',
  );
}
