// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRMOmda9aoaPX-mLdcykzvWKsbuP8uzu4',
    appId: '1:191448713040:android:05e4f50a24b25a6eefce55',
    messagingSenderId: '191448713040',
    projectId: 'bday--2022',
    storageBucket: 'bday--2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT_ADJFSFUH0qnu9Ib52mIZjFDvWNfQtk',
    appId: '1:191448713040:ios:0080f43dc4b63246efce55',
    messagingSenderId: '191448713040',
    projectId: 'bday--2022',
    storageBucket: 'bday--2022.appspot.com',
    androidClientId: '191448713040-vnj6vd4mjmqam5fliclucr3jkj56gm71.apps.googleusercontent.com',
    iosClientId: '191448713040-l8hoscls21vs1a1hvejqk5lfgti78j40.apps.googleusercontent.com',
    iosBundleId: 'it.giuug.bday',
  );
}
